name: Feature request
description: Suggest an idea for this project
labels: ["feature request"]
body:
  
  - type: textarea
    id: question1
    attributes:
      label: Is your feature related to a problem?
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: question2
    attributes:
      label: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: question3
    attributes:
      label: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
  - type: textarea
    id: question4
    attributes:
      label: Additional context
      placeholder: Add any other context about the feature request here.
    validations:
      required: false

